import { chromium } from 'playwright'
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } })
const page = await ctx.newPage()
page.on('console', m => console.log('[' + m.type() + ']', m.text()))
page.on('pageerror', e => console.log('[pageerror]', e.message))
await page.goto('http://localhost:3000/login', { waitUntil: 'networkidle' })
await page.locator('input[type="email"]').fill('hans@test.com')
await page.locator('input[type="password"]').fill('Test123456')
await page.locator('button:has-text("登录")').click()
await page.waitForURL('**/workbench', { timeout: 10_000 })
await page.waitForTimeout(3500)
console.log('--- click chan toggle ---')
await page.locator('button[title*="缠论"]').first().click()
await page.waitForTimeout(4000)
console.log('--- done ---')
await ctx.close()
await browser.close()
